name: Preview Flask App via ngrok

on:
  push:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # Install ngrok CLI
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok

      - name: Install latest ngrok
        run: |
            # Remove old ngrok if exists
            sudo rm -f /usr/local/bin/ngrok || true

            # Download latest version
            curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz
            tar -xvzf ngrok.tgz
            chmod +x ngrok
            sudo mv ngrok /usr/local/bin/ngrok

            # Verify version
            ngrok version

      - name: Start Flask app
        run: |
          # Run Flask app in background
          python __init__.py &
          FLASK_PID=$!

          # Wait a few seconds for Flask to start
          sleep 5

          # Start ngrok tunnel to port 5000
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ./ngrok http 5000 &
          NGROK_PID=$!

          # Wait for ngrok to initialize
          sleep 5

          # Fetch ngrok public URL
          NGROK_URL=$(curl --silent --show-error http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Your temporary preview URL: $NGROK_URL"

          # Keep the preview alive for 120 seconds
          sleep 120

          # Kill Flask and ngrok processes
          kill $FLASK_PID $NGROK_PID
