name: Preview Flask App via ngrok

on:
  push:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t flask-ngrok-app .

      - name: Run Flask app and show ngrok URL
        run: |
          # Run container in background
          CONTAINER_ID=$(docker run -d -p 5000:5000 flask-ngrok-app)

          # Wait a few seconds for ngrok to start
          sleep 15

          # Extract the ngrok URL from container logs
          NGROK_URL=$(docker logs $CONTAINER_ID 2>&1 | grep -o 'https://[a-z0-9]*\.ngrok.io')
          echo "Your temporary preview URL: $NGROK_URL"

          # Keep container alive for 120 seconds
          sleep 120

          # Stop the container
          docker stop $CONTAINER_ID
