name: Build and Deploy Flask App with Ngrok

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t flask-ngrok-app .

      - name: Run Flask app in Docker and show ngrok URL
        run: |
            # Run the container in detached mode
            CONTAINER_ID=$(docker run -d -p 5000:5000 flask-ngrok-app)

            # Wait for Flask + ngrok to start
            echo "Waiting 15 seconds for ngrok to initialize..."
            sleep 15

            # Show the ngrok URL from container logs
            docker logs $CONTAINER_ID | grep -o 'https://[a-z0-9]*\.ngrok.io'

            # Keep the container alive for 120 seconds
            sleep 120